ccf = cc -Wall -Wextra -Werror

all:
	$(ccf) execute_child.c init_stdio.c main_bonus.c pipex.c setup_child.c utils.c -I ../include ../libft/libft.a ../get_next_line/get_next_line.c ../get_next_line/get_next_line_utils.c heredoc.c
