ccf = cc -Wall -Wextra -Werror

all:
	$(ccf) -I ../include heredoc.c execute_child.c init_stdio.c main_bonus.c pipex.c create_child.c utils.c ../get_next_line/get_next_line.c ../get_next_line/get_next_line_utils.c ../libft/libft.a -o pipex
